# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  PORT: 7867
  MONGODB_URI: mongodb://stonomodb:27017/stonomo
  TOKEN_SECRET_FILE: secrets/token_secret.txt
  NODE_ENV: development
  BCRYPT_SALT: 10
  CLIENT_URL: localhost:8080
  EMAIL_HOST: smtp.mailgun.org
  EMAIL_PORT: 587
  EMAIL_USERNAME: postmaster@sandbox8cad89a5ea9f4ec8a3f505b85704972a.mailgun.org
  EMAIL_PASSWORD: 824abb8a7117032b2f6bdad9d238fec2-4b670513-dcdb7e9e
  FROM_EMAIL: stonomollc@gmail.com

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - run: npm install
    - run: npm run build --if-present
    - run: npm test --if-present

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: node-app
        path: .
      
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'Stonomo-backend'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }} # Publish profile should always be stored as secrets in your repository Settings - Secrets and variables - Actions - secrets
          package: .