# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - stonomo-test

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://stonomo.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_402eba7a510948429e077da9617fc9f5 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_f643ed6513bf4e5d9254614dfbb3f3fc }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: stonomo.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_402eba7a510948429e077da9617fc9f5 }}/samples/stonomoapi:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'stonomo-test'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_f90c5ebc4e97414cb6d9c3aa4576aa82 }}
        images: 'stonomo.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_402eba7a510948429e077da9617fc9f5 }}/samples/stonomoapi:${{ github.sha }}'