# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - stonomo-test

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to registry
      uses: docker/login-action@v3
      with:
        registry: https://stonomo.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_3fb2f1b1020b4d389df3ddc0ce41a114 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_7789f4348f14465f9eb38df0d1514f0d }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: stonomo.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_3fb2f1b1020b4d389df3ddc0ce41a114 }}/stonomo/samples/stonomoapi:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v3
      with:
        app-name: 'stonomo-test'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_7e29d6bddd084a659c7cf977c893874b }}
        images: 'stonomo.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_3fb2f1b1020b4d389df3ddc0ce41a114 }}/stonomo/samples/stonomoapi:${{ github.sha }}'